## arithmatic operation in array 

In [1]:
import numpy as np

In [3]:
ar1= np.array([1,2,3,4]) 

ar1+10

array([11, 12, 13, 14])

In [5]:
ar1= np.array([1,2,3,4]) 
ar2= np.array([1,2,3,4]) 


arradd= ar1+ar2
print(arradd)

[2 4 6 8]


In [6]:
ar1= np.array([1,2,3,4]) 

ar1- 10

array([-9, -8, -7, -6])

In [7]:
ar1= np.array([1,2,3,4]) 
ar2= np.array([1,2,3,4]) 


arradd= ar1 - ar2
print(arradd)

[0 0 0 0]


In [8]:
ar1= np.array([1,2,3,4]) 

ar1 * 10

array([10, 20, 30, 40])

In [9]:
ar1= np.array([1,2,3,4]) 
ar2= np.array([1,2,3,4]) 


arradd= ar1 * ar2
print(arradd)

[ 1  4  9 16]


In [10]:
ar1= np.array([1,2,3,4]) 
ar2= np.array([1,2,3,4]) 


arradd= ar1 / ar2
print(arradd)

[1. 1. 1. 1.]


In [12]:
ar1= np.array([10,20,30,40]) 

ar1 % 3

array([1, 2, 0, 1], dtype=int32)

In [14]:
ar1= np.array([2,3,4,5]) 

ar1 ** 2

array([ 4,  9, 16, 25])

In [15]:
ar1= np.array([2,3,4,5]) 

ar1 ** 3

array([  8,  27,  64, 125], dtype=int32)

In [ ]:
## by using function 

In [27]:
ar1= np.array([2,3,4,5]) 

ar1=np.add(ar1,3)

print(ar1)

[5 6 7 8]


In [30]:
ar1= np.array([1,3,4,5])       # a/1 

ar1=np.reciprocal(ar1)

print(ar1)

[1 0 0 0]


In [16]:
ar1= np.array([1,2,3,4]) 
ar2= np.array([1,2,3,4]) 


arradd= np.add(ar1,ar2)
print(arradd)

[2 4 6 8]


In [19]:
ar1= np.array([1,2,3,4]) 
ar2= np.array([1,2,3,4]) 


arradd= np.add(ar1 , 100)
print(arradd)

[101 102 103 104]


In [17]:
ar1= np.array([1,2,3,4]) 
ar2= np.array([1,2,3,4]) 


arradd= np.multiply(ar1,ar2)
print(arradd)

[ 1  4  9 16]


In [18]:
ar1= np.array([1,2,3,4]) 
ar2= np.array([1,2,3,4]) 


arradd= np.divide(ar1,ar2)
print(arradd)

[1. 1. 1. 1.]


### 2d array 

In [23]:
ar1 = np.array([ [1,2,3,4],
                 [5,6,7,8]])


ar2 = np.array([ [1,2,3,4],
                 [5,6,7,8]]) 

varadd = ar1+ar2 

print(varadd)

[[ 2  4  6  8]
 [10 12 14 16]]


In [24]:
ar1 = np.array([ [1,2,3,4],
                 [5,6,7,8]])


ar2 = np.array([ [1,2,3,4],
                 [5,6,7,8]]) 

varadd = ar1 * ar2 

print(varadd)

[[ 1  4  9 16]
 [25 36 49 64]]


## arithmatic function in numpy array 

In [33]:
ar1= np.array([1,2,3,4,5,6,7,8,9,13]) 

print(ar1)

[ 1  2  3  4  5  6  7  8  9 13]


In [34]:
np.min(ar1)

1

In [35]:
np.max(ar1)

13

In [36]:
np.argmax(ar1)   # index 

9

In [38]:
np.argmin(ar1)  # index 

0

In [51]:
np.sqrt(ar1)

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
         2.44948974,  2.64575131,  2.82842712,  3.        ,  3.60555128],
       [ 6.70820393,  8.18535277,  9.43398113,  5.65685425,  5.83095189,
        23.36664289,  0.        ,  8.83176087,  4.58257569,  3.46410162]])

In [54]:
np.sin(ar1)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,  0.42016704],
       [ 0.85090352, -0.85551998,  0.86006941,  0.55142668,  0.52908269,
        -0.59488432,  0.        ,  0.51397846,  0.83665564, -0.53657292]])

In [56]:
np.cos(ar1)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
         0.96017029,  0.75390225, -0.14550003, -0.91113026,  0.90744678],
       [ 0.52532199, -0.5177698 ,  0.51017704,  0.83422336, -0.84857027,
         0.80381133,  1.        , -0.85780309, -0.54772926,  0.84385396]])

In [57]:
np.tan(ar1)

array([[ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
        -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.46302113],
       [ 1.61977519,  1.65231726,  1.68582537,  0.66100604, -0.62349896,
        -0.74007954,  0.        , -0.59918   , -1.52749853, -0.63585993]])

In [58]:
ar1= np.array([1,2,3,4,5,6,7,8,9,13])  # addition of evry index one by one 

np.cumsum(ar1)  

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 58])

In [59]:
ar1= np.array( [ [1,2,3,4,5,6,7,8,9,13] , [45,67,89,32,34,546,0,78,21,12] ])  

print(ar1)

[[  1   2   3   4   5   6   7   8   9  13]
 [ 45  67  89  32  34 546   0  78  21  12]]


In [46]:
print(np.min(ar1 , axis=1) )                    # axis = 1 (row)

[1 0]


In [47]:
print(np.max(ar1 , axis=1) ) 

[ 13 546]


In [48]:
print(np.max(ar1 , axis=0) )                            # axis = 0 (column)

[ 45  67  89  32  34 546   7  78  21  13]


In [49]:
print(np.min(ar1 , axis=0) )  

[ 1  2  3  4  5  6  0  8  9 12]


In [53]:
print(np.sqrt(ar1 ) ) 

[[ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
   2.64575131  2.82842712  3.          3.60555128]
 [ 6.70820393  8.18535277  9.43398113  5.65685425  5.83095189 23.36664289
   0.          8.83176087  4.58257569  3.46410162]]


In [60]:
ar1= np.cumsum( [ [1,2,3,4,5,6,7,8,9,13] , [45,67,89,32,34,546,0,78,21,12] ])  

print(ar1)

[  1   3   6  10  15  21  28  36  45  58 103 170 259 291 325 871 871 949
 970 982]
