In [2]:
import numpy as np

In [3]:

list1=[4,5,6,7] 
arr = np.array(list1)   # <--- 

print(arr)  

print(type(arr)) 

[4 5 6 7]
<class 'numpy.ndarray'>


In [4]:
arr.ndim

1

In [6]:
ar2=np.array([[1,2,3], [2,3,4] ,[5,6,7]])
ar2.ndim

2

In [9]:
ar3=np.array([ [ [1,2,3] ,[4,5,6] , [6,7,8] ] ])
ar3.ndim

3

In [10]:
print(ar3)

[[[1 2 3]
  [4 5 6]
  [6 7 8]]]


In [ ]:
# if you want to crete n dimention array then, 

In [11]:
arn= np.array([1,2,3,4,5] , ndmin=10)   # 10 dimention array 
print(arn)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]


In [12]:
arn.ndim

10

In [ ]:
# how we can create numpy array by using numpy function 

# array filled with 0 

In [13]:
ar_z= np.zeros(6) 
print(ar_z)



[0. 0. 0. 0. 0. 0.]


In [15]:
ar_z2= np.zeros((3,4)) 
print(ar_z2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
ar_z3= np.zeros((3,4,1)) 
print(ar_z3)

[[[0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]]]


# array filled with 1

In [17]:
ar_o=np.ones(5)
print(ar_o)

[1. 1. 1. 1. 1.]


In [20]:
ar_2=np.ones((4,5))
print(ar_2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
ar_3=np.ones((3,3,1))
print(ar_3)

[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]


# create an empty array 

In [23]:
ar_em = np.empty(4)

print(ar_em)

[2.12199579e-314 1.08646184e-311 7.58884832e-321 1.08646185e-311]


## create range of array 

In [24]:
ar_arr=np.arange(8)
print(ar_arr)

[0 1 2 3 4 5 6 7]


In [28]:
ar_arr2=np.arange(1,20,2)
print(ar_arr2)

[ 1  3  5  7  9 11 13 15 17 19]


## array of diagonal elements filled with 1 

In [29]:
ar_dia=np.eye(5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
ar_dia5=np.eye(3,5)
print(ar_dia5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## create a numpy array with random number 

## rand

In [34]:
r_no=np.random.rand(6)   # it will give you random  6 value bet 0 - 1  it wiill give you no +ve (positive)

print(r_no)

[0.40073371 0.03956808 0.27698259 0.28131599 0.22127135 0.64200489]


In [36]:
r_no1=np.random.rand(3,5)
r_no1

array([[0.97945269, 0.57731913, 0.83399635, 0.24427151, 0.40698266],
       [0.75736647, 0.99142556, 0.40262637, 0.76581543, 0.52824163],
       [0.08530641, 0.9113153 , 0.33002888, 0.4303158 , 0.11377718]])

## randn

In [39]:
r_n=np.random.randn(5)    # it will give you random  5 value bet 0 - 1  it wiill give you no positive & negative
r_n

array([-0.01105571, -0.42414866,  0.62127754, -1.0585741 ,  0.03799444])

In [40]:
r_n1=np.random.randn(3,3)    # it will give you random  5 value bet 0 - 1  it wiill give you no positive & negative
r_n1

array([[ 0.53540205,  0.41002501, -0.6033892 ],
       [ 0.37118091, -0.69955154, -0.21105254],
       [ 0.76749085,  0.96978378,  2.05022923]])

## ranf

In [41]:
ar_f=np.random.ranf(6)
ar_f

array([0.11665576, 0.72654959, 0.37622753, 0.44384137, 0.59361097,
       0.05446201])

## randint

In [ ]:
r_int=np.random.randint(min,max,total_val)


In [42]:
r_int=np.random.randint(1,10)
r_int

6

In [43]:
r_int=np.random.randint(1,10,2)
r_int

array([5, 1])

In [44]:
r_int=np.random.randint(1,10,5)
r_int

array([9, 7, 2, 4, 3])

## Numpy datatype

In [48]:
arr1=np.array([2,3,4,5]) 

print(arr1.dtype)

int32


In [50]:
new= np.float32(arr1) 
print(new.dtype)

float32


In [54]:
arr5 = np.array([2,3,4,5,6]) 

print(arr5.dtype) 
print(arr5)

new1= arr5.astype(float) 

print(new1.dtype) 
print(new1)

int32
[2 3 4 5 6]
float64
[2. 3. 4. 5. 6.]


In [45]:


# Creating a NumPy array with default data type (int)
arr_default = np.array([1, 2, 3, 4, 5])
print("Array:", arr_default)
print("Default Data Type:", arr_default.dtype)



Array: [1 2 3 4 5]
Default Data Type: int32


In [46]:


# Creating a NumPy array with a specific data type (float)
arr_float = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.float64)
print("Array:", arr_float)
print("Custom Data Type (float):", arr_float.dtype)


Array: [1.1 2.2 3.3 4.4 5.5]
Custom Data Type (float): float64


In [47]:



arr_int = np.array([1, 2, 3, 4, 5])

# Converting the array to float
arr_float = arr_int.astype(np.float64)

print("Original Array (int):", arr_int)
print("Converted Array (float):", arr_float)


Original Array (int): [1 2 3 4 5]
Converted Array (float): [1. 2. 3. 4. 5.]
