In [1]:
import numpy as np

## insert

In [2]:
ar1= np.array([4,5,6,7,8,0,0,6,1] ) 

x=np.insert(ar1 , 1 , 1000)     # insert(ar1 , index , val) 
print(x)

[   4 1000    5    6    7    8    0    0    6    1]


In [3]:
ar1= np.array([4,5,6,7,8,0,0,6,1] ) 

x=np.insert(ar1 ,(5,6), 1000)     # insert(ar1 , index , val) 
print(x)

[   4    5    6    7    8 1000    0 1000    0    6    1]


In [5]:
ar2= np.array([[1,2,3] ,
               [2,3,45] ] )   


v1=np.insert(ar2 , 2 , (22,34,56) , axis=0) 


print(v1)

[[ 1  2  3]
 [ 2  3 45]
 [22 34 56]]


In [8]:
ar2= np.array([[1,2,3] ,
               [2,3,45] ] )   


v1=np.insert(ar2 , 2, (22,34) , axis=1) 


print(v1)

[[ 1  2 22  3]
 [ 2  3 34 45]]


## append

In [9]:
ar1= np.array([4,5,6,7,8,0,0,6,1] ) 

z=np.append(ar1 , 100)

print(z)

[  4   5   6   7   8   0   0   6   1 100]


In [14]:
ar2= np.array([[1,2,3] ,
               [2,3,45] ] )   


x= np.append(ar2 ,[[88, 99,111]] ,axis=0) 
print(x)

[[  1   2   3]
 [  2   3  45]
 [ 88  99 111]]


In [19]:
import numpy as np

ar2 = np.array([[1, 2, 3], [2, 3, 45]])


new_row = np.array([[2, 50]]).T

x = np.append(ar2, new_row, axis=1)

print(x)


[[ 1  2  3  2]
 [ 2  3 45 50]]


## delete

In [22]:
ar1= np.array([4,5,6,7,8,0,0,6,1] ) 

print(ar1) 


d= np.delete(ar1 , 0 )   # index 

print(d)

[4 5 6 7 8 0 0 6 1]
[5 6 7 8 0 0 6 1]
