### indexing & slicing

In [4]:
import numpy as np

In [6]:
arr = np.array([2,3,4,5]) 

arr[3]

5

In [7]:
# change element of array on index 3

arr[3]=10 
arr

array([ 2,  3,  4, 10])

In [8]:
arr[1:]

array([ 3,  4, 10])

In [9]:
arr[-1]

10

In [10]:
arr[:-1]

array([2, 3, 4])

In [11]:
arr[::-1]  #  it reverse all element 

array([10,  4,  3,  2])

In [12]:
lst1=[1,2,3,5,6]
lst2=[5,6,7,8,0] 
lst3=[8,9,4,5,7] 


arr2d=np.array([lst1,lst2,lst3]) 

print(arr2d) 

[[1 2 3 5 6]
 [5 6 7 8 0]
 [8 9 4 5 7]]


In [13]:
arr2d.ndim

2

In [14]:
arr2d[:,1]    # [row , column ]   [ : , 1th column]

array([2, 6, 9])

In [15]:
arr2d[ 1:,1:3]

array([[6, 7],
       [9, 4]])

In [17]:
# 3d array  

ar3=np.array([  [ [1,2,3], 
                  [4,5,6],
                  [6,7,8]   ]]) 

ar3.ndim

3

In [19]:
ar3[0 ,1: , 2]

array([6, 8])

In [1]:
import numpy as np


arr_1d = np.array([1, 2, 3, 4, 5])


first_element = arr_1d[0]
third_element = arr_1d[2]

print("Original Array:", arr_1d)
print("First Element:", first_element)
print("Third Element:", third_element)


Original Array: [1 2 3 4 5]
First Element: 1
Third Element: 3


In [2]:
import numpy as np


arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element_1_1 = arr_2d[0, 0] 
element_2_3 = arr_2d[1, 2]  


print("Original Array:")
print(arr_2d)
print("Element at (0, 0):", element_1_1)
print("Element at (1, 2):", element_2_3)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (0, 0): 1
Element at (1, 2): 6


In [3]:
import numpy as np


arr_3d = np.array([[ [1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9] ],
                   
                   [[10, 11, 12], 
                    [13, 14, 15],
                    [16, 17, 18]],
                   
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27] ] ])


element_1_1_1 = arr_3d[0, 0, 0]  # Layer 0, Row 0, Column 0
element_2_2_3 = arr_3d[1, 1, 2]  


print("Original 3D Array:")
print(arr_3d)
print("Element at (0, 0, 0):", element_1_1_1)
print("Element at (1, 1, 2):", element_2_2_3)


Original 3D Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Element at (0, 0, 0): 1
Element at (1, 1, 2): 15


## Itreation in array 

In [21]:
ar1= np.array([1,2,788,8,9,3]) 

for i in ar1 :
    print(i)

1
2
788
8
9
3


In [24]:
ar2= np.array([[1,2,3,4,5] ,
               [2,3,45,5,6] ,
               [1,2,3,4,5]])  

for i in ar2 :
    print(i)

[1 2 3 4 5]
[ 2  3 45  5  6]
[1 2 3 4 5]


In [25]:
for j in ar2 :
    for k in j :
        print(k)

1
2
3
4
5
2
3
45
5
6
1
2
3
4
5


In [32]:
# for 3d array
ar3 = np.array([[ [3,4,5,6,7] ,
                  [1,2,3,4,5], 
                  [4,9,7,1,3] ]]) 

print(ar3.ndim)
print(ar3.shape)

3
(1, 3, 5)


In [35]:
for i in ar3 :
    print(i)

[[3 4 5 6 7]
 [1 2 3 4 5]
 [4 9 7 1 3]]


In [36]:
for i in ar3 :
    for j in i :
        for  k in j :
            print(k)

3
4
5
6
7
1
2
3
4
5
4
9
7
1
3


In [ ]:
# with using function 

In [37]:
# for 3d array
ar3 = np.array([[ [3,4,5,6,7] ,
                  [1,2,3,4,5], 
                  [4,9,7,1,3] ]]) 

print(ar3.ndim)
print(ar3.shape)

3
(1, 3, 5)


In [38]:
for i in np.nditer(ar3):
    print(i)

3
4
5
6
7
1
2
3
4
5
4
9
7
1
3


In [39]:
# iterating with index number 


# for 3d array
ar4 = np.array([[ [3,4,5,6,7] ,
                  [1,2,3,4,5], 
                  [4,9,7,1,3] ]]) 



for i in np.ndenumerate(ar4):
    print(i)

((0, 0, 0), 3)
((0, 0, 1), 4)
((0, 0, 2), 5)
((0, 0, 3), 6)
((0, 0, 4), 7)
((0, 1, 0), 1)
((0, 1, 1), 2)
((0, 1, 2), 3)
((0, 1, 3), 4)
((0, 1, 4), 5)
((0, 2, 0), 4)
((0, 2, 1), 9)
((0, 2, 2), 7)
((0, 2, 3), 1)
((0, 2, 4), 3)


In [41]:
ar2= np.array([[1,2,3,4,5] ,
               [2,3,45,5,6] ,
               [1,2,3,4,5]] )  

for i in np.ndenumerate(ar2) :
    print(i)
  

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((0, 4), 5)
((1, 0), 2)
((1, 1), 3)
((1, 2), 45)
((1, 3), 5)
((1, 4), 6)
((2, 0), 1)
((2, 1), 2)
((2, 2), 3)
((2, 3), 4)
((2, 4), 5)


## copy  & view

In [42]:
# copy

ar2= np.array([[1,2,3,4,5] ,
               [2,3,45,5,6] ,
               [1,2,3,4,5]] )   


co= np.copy(ar2) 

print(co)


[[ 1  2  3  4  5]
 [ 2  3 45  5  6]
 [ 1  2  3  4  5]]


In [44]:
# view 

ar2= np.array([[1,2,3,4,5] ,
               [2,3,45,5,6] ,
               [1,2,3,4,5]] )    


vi = ar2.view()
print(vi)


[[ 1  2  3  4  5]
 [ 2  3 45  5  6]
 [ 1  2  3  4  5]]


In [ ]:
# diff copy vs view 

# copy have it own data 

# view dont have it own data 

In [ ]:
# if you have project you want to make copy of but you want to make changes in that copy only use np.copy 

# if you have project you want to make copy of but you want to make changes in that original copy and duplicate  also  use view  