## Numpy 

In [ ]:
# 1)  NumPy is a powerful library in Python for numerical and vide mathematical operations 

# 2)  One of its key features is the NumPy array, which is a multi-dimensional array 
#   that provides efficient storage and manipulation of homogeneous data 

# 3) # An array is a data structure that stores a collection of elements,
# where each element can be accessed using an index or a key.  
# and array in python can only conatain value corresponding to "same" data type  where the list in containall data types 

In [ ]:
# list vs array 

# array consume lesss memory 
# fast 
# easy to use  
# it work as matrix 

# list is comma separated and array is without comma 

In [2]:
import numpy as np

In [ ]:
# basic array 

In [8]:
list1= [1,2,3,4,5]   #<--  list 

print(type(list1))    # look 

<class 'list'>


In [9]:
# convert list into array 

list1=[4,5,6,7] 
arr = np.array(list1)   # <--- 

print(arr)  

print(type(arr))    # look 

[4 5 6 7]
<class 'numpy.ndarray'>


In [10]:
arr.shape

(4,)

In [154]:
# to check dimention of array 

arr.ndim

1

In [153]:
l=[] 

for i in range(1,6):
    no=int(input("enter no :")) 
    l.append(no) 
    

print(np.array(l))

[5 8 7 2 6]


In [ ]:
# 2 dimentional array 

In [160]:
ar2= np.array([ [1,2,4] ,[4,6,8] , [ 3,5,7] ]) 

print(ar2) 

print('\n')
print(ar2.ndim)


[[1 2 4]
 [4 6 8]
 [3 5 7]]


2


In [14]:
lst1=[1,2,3,5,6]
lst2=[5,6,7,8,0] 
lst3=[8,9,4,5,7] 


arr2d=np.array([lst1,lst2,lst3]) 

print(arr2d)  
print("\n")
print(type(arr2d))

[[1 2 3 5 6]
 [5 6 7 8 0]
 [8 9 4 5 7]]


<class 'numpy.ndarray'>


In [16]:
arr2d.shape  # it is 2d array it have 3 rows and 5 column 

(3, 5)

In [155]:
arr2d.ndim

2

In [17]:
# indexing of array 

In [18]:
arr

array([4, 5, 6, 7])

In [21]:
arr[3] 


7

In [24]:
# change element of array on index 3

arr[3]=10 
arr

array([ 4,  5,  6, 10])

In [25]:
arr[1:]

array([ 5,  6, 10])

In [26]:
arr[-1]

10

In [27]:
arr[:-1]

array([4, 5, 6])

In [28]:
arr[::-1]  #  it reverse all element 

array([10,  6,  5,  4])

In [ ]:
# for3d and  multidimentional 

In [164]:
arr2d

array([[1, 2, 3, 5, 6],
       [5, 6, 7, 8, 0],
       [8, 9, 4, 5, 7]])

In [165]:
arr2d.ndim

2

In [166]:
# 3d array  

ar3=np.array([  [ [1,2,3], 
                  [4,5,6],
                  [6,7,8]   ]])

In [167]:
ar3.ndim

3

In [163]:
arr2d[:,1]    # [row , column ]   [ : , 1th column]

array([2, 6, 9])

In [ ]:
# to get 
# [6,7 
#  9,4]

In [32]:
arr2d[1: , 1:3]

array([[6, 7],
       [9, 4]])

In [33]:
arr2d

array([[1, 2, 3, 5, 6],
       [5, 6, 7, 8, 0],
       [8, 9, 4, 5, 7]])

In [35]:
arr2d[0:2,3:]                   # 5,6
                                # 8,0

array([[5, 6],
       [8, 0]])

In [36]:
# 9,4 

arr2d[2,1:3]

array([9, 4])

In [37]:
# 7
arr2d[2 , 4]

7

In [39]:
arr2d

array([[1, 2, 3, 5, 6],
       [5, 6, 7, 8, 0],
       [8, 9, 4, 5, 7]])

In [63]:
arr2d[ : , -1:]

array([[6],
       [0],
       [7]])

In [46]:
# get last 2 column
last2=arr2d[: , 3:]

In [49]:
last2

array([[5, 6],
       [8, 0],
       [5, 7]])

In [48]:
last2.shape

(3, 2)

In [ ]:
# EDA for Array 

In [69]:
arr1=[1,2,3,4,5,6,7,8,9] 

arr1=np.array(arr1) 

type(arr1)

numpy.ndarray

In [70]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr1<3            # it will data and give ans in term of true or false 

array([ True,  True, False, False, False, False, False, False, False])

In [73]:
arr1>8

array([False, False, False, False, False, False, False, False,  True])

In [74]:
arr1[arr1>8]

array([9])

In [75]:
arr1[arr1<3]

array([1, 2])

In [76]:
arr2d

array([[1, 2, 3, 5, 6],
       [5, 6, 7, 8, 0],
       [8, 9, 4, 5, 7]])

In [79]:
arr2d.shape   # can we fix these shape to (5,3)  ? , yes

(3, 5)

In [81]:
arr2d.reshape(5,3)        # look 

array([[1, 2, 3],
       [5, 6, 5],
       [6, 7, 8],
       [0, 8, 9],
       [4, 5, 7]])

In [83]:
# if we do (5,4)  it will raise error 

arr2d.reshape(5,4)                # cause 5x3 = 15 , 3x5 = 15 ,  5x4 = 20

ValueError: cannot reshape array of size 15 into shape (5,4)

In [ ]:
# method to create array automaticall 

In [85]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
# we can arrange above array in term of 2d  

np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [96]:
np.arange(1,20,2).reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [99]:
np.arange(2,21,2).reshape(2,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [103]:
np.arange(0,10,1).reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [106]:
arr2=np.arange(1,11,1).reshape(1,10)

In [109]:
print(arr2)
print(type(arr2))

[[ 1  2  3  4  5  6  7  8  9 10]]
<class 'numpy.ndarray'>


In [ ]:
# we can convert these array in term of 3d also 

In [111]:
np.arange(1,11,1).reshape(1,10,1)   # 3d array it has 3[]

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [118]:
np.arange(2,21,2).reshape(2,5,1)   # it is 3d array

array([[[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]],

       [[12],
        [14],
        [16],
        [18],
        [20]]])

In [119]:
# array operation 

In [122]:
arr4=[1,2,3,4,5]
arr4=np.array(arr4)

In [123]:
arr4 * arr4

array([ 1,  4,  9, 16, 25])

In [124]:
arr2d * 2

array([[ 2,  4,  6, 10, 12],
       [10, 12, 14, 16,  0],
       [16, 18,  8, 10, 14]])

In [125]:
arr2d * arr2d

array([[ 1,  4,  9, 25, 36],
       [25, 36, 49, 64,  0],
       [64, 81, 16, 25, 49]])

In [126]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [128]:
np.zeros((6,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# intiallizing random no for array 

In [133]:
np.random.randint(1,30) # it give you 1 random  no 

23

In [134]:
np.random.randint(1,30,5) # it give you 5 random  no

array([25, 11,  9, 25,  7])

In [136]:
np.random.randint(1,20,4).reshape(2,2)   # you can reshape it 

array([[ 6,  3],
       [ 7, 11]])

In [141]:
np.random.randn(1,20)                             # based on normal distribution

array([[-0.47014544, -2.52993276, -0.94036904,  1.3517242 , -0.31552917,
        -0.50252291,  0.59357173, -0.99376447, -0.73384613, -0.46729145,
        -1.10744878, -0.24530577,  0.27187152,  1.5329764 ,  0.63056814,
        -0.22149849,  1.19001796,  1.51319883, -0.56653128, -1.44839903]])

In [144]:
np.random.random_sample((3,5))         # it wil initialize no size between  0 - 1 

array([[0.60090454, 0.05984977, 0.6543649 , 0.26239485, 0.09544278],
       [0.66292486, 0.12245379, 0.10681994, 0.73567739, 0.63484423],
       [0.87196242, 0.81606619, 0.29503648, 0.10485729, 0.6649933 ]])

In [151]:
np.random.random_sample((10,5))

array([[0.22750555, 0.00430569, 0.79447412, 0.16773903, 0.27204497],
       [0.12602213, 0.43632571, 0.1337469 , 0.4038464 , 0.37957262],
       [0.97092685, 0.10917198, 0.16672983, 0.87198318, 0.13667727],
       [0.83002447, 0.14682172, 0.8188545 , 0.41743674, 0.20459256],
       [0.49772405, 0.29595611, 0.71433023, 0.53853181, 0.72271683],
       [0.98325566, 0.08585767, 0.4603015 , 0.81616541, 0.8958124 ],
       [0.09833173, 0.39914434, 0.26093419, 0.91839572, 0.96357971],
       [0.89976933, 0.53362174, 0.99000424, 0.55858263, 0.66693126],
       [0.73765696, 0.39799761, 0.44326508, 0.17094907, 0.38123443],
       [0.99775406, 0.40848748, 0.280986  , 0.879399  , 0.11284527]])