# join : puttin content two or more array in single array 

In [2]:
import numpy as np

In [4]:
ar1= np.array([1,2,3,4,5,6,7,8,9,10,11,12] )  
ar2= np.array([4,5,6,7,8,9,0,1,2,3,4,4,6] ) 

arr=np.concatenate((ar1,ar2)) 

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12  4  5  6  7  8  9  0  1  2  3  4  4
  6]


In [ ]:
# for 2d 

In [5]:
ar2= np.array([[1,2,3,4,5] ,
               [2,3,45,5,6] ,
               [1,2,3,4,5]] )   


ar3= np.array([[1,2,3,4,5] ,
               [2,3,45,5,6] ,
               [1,2,3,4,5]] ) 

add=np.concatenate((ar2,ar3)) 

print(add)

[[ 1  2  3  4  5]
 [ 2  3 45  5  6]
 [ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 2  3 45  5  6]
 [ 1  2  3  4  5]]


In [8]:
# we are merging with it row axis 


ar2= np.array([[1,2,3,4,5] ,
               [2,3,45,5,6] ,
               [1,2,3,4,5]] )   


ar3= np.array([[1,2,3,4,5] ,
               [2,3,45,5,6] ,
               [1,2,3,4,5]] ) 

add_new=np.concatenate((ar2,ar3) , axis=1)  

print(add_new)


[[ 1  2  3  4  5  1  2  3  4  5]
 [ 2  3 45  5  6  2  3 45  5  6]
 [ 1  2  3  4  5  1  2  3  4  5]]


In [9]:
# we are merging with it col axis 


ar2= np.array([[1,2,3,4,5] ,
               [2,3,45,5,6] ,
               [1,2,3,4,5]] )   


ar3= np.array([[1,2,3,4,5] ,
               [2,3,45,5,6] ,
               [1,2,3,4,5]] ) 

add_new=np.concatenate((ar2,ar3) , axis=0)  

print(add_new)

[[ 1  2  3  4  5]
 [ 2  3 45  5  6]
 [ 1  2  3  4  5]
 [ 1  2  3  4  5]
 [ 2  3 45  5  6]
 [ 1  2  3  4  5]]


In [ ]:
# by using stack function 

In [13]:
ar2= np.array([[1,2,3,4,5] ,
               [2,3,45,5,6] 
               ] )   


ar3= np.array([[1,2,3,4,5] ,
               [2,3,45,5,6] ] ) 

a_new=np.stack((ar2,ar3) , axis=0)  

print(a_new)

[[[ 1  2  3  4  5]
  [ 2  3 45  5  6]]

 [[ 1  2  3  4  5]
  [ 2  3 45  5  6]]]


In [14]:
ar2= np.array([[1,2] ,
               [2,3] 
               ] )   


ar3= np.array([[1,2] ,
               [2,3] ] ) 

a_new=np.stack((ar2,ar3) , axis=1)  

print(a_new)

[[[1 2]
  [1 2]]

 [[2 3]
  [2 3]]]


In [16]:
ar1= np.array([1,2,3,4,5,6] )  
ar2= np.array([4,5,6,7,8,9] ) 

arr=np.stack((ar1,ar2) ,axis=0) 

print(arr)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


## split array

In [17]:
ar1= np.array([1,2,3,4,5,6,7,8,9] ) 

n_ar = np.array_split(ar1 , 3) 

print(n_ar)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [19]:
ar1= np.array( [ [1,2],[3,4] ,[5,6] ,[7,8] ] ) 

n_ar = np.array_split(ar1 , 2) 

print(n_ar)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


## search array 

In [20]:
ar2= np.array([4,5,6,7,8,9,0,1,2,3,4,4,6] )   

x=np.where(ar2==0) 
print(x)



(array([6], dtype=int64),)


In [21]:
ar2= np.array([4,5,6,7,8,9,0,1,2,3,4,4,6] )   

x=np.where(ar2==4) 
print(x)


(array([ 0, 10, 11], dtype=int64),)


In [28]:
ar2= np.array([4,5,6,7,8,0,0,6,1,2,3,4,4,6] )   

xn=np.where( (ar2 / 6== 0)) 
print(xn)


(array([5, 6], dtype=int64),)


In [29]:
ar2= np.array([4,5,6,7,8,0,0,6,1,2,3,4,4,6] )   

xn=np.where( (ar2 % 2== 0)) 
print(xn)


(array([ 0,  2,  4,  5,  6,  7,  9, 11, 12, 13], dtype=int64),)


In [30]:
ar2= np.array([4,5,6,7,8,0,0,6,1,2,3,4,4,6] )   

xn=np.where( (ar2 % 2 != 0)) 
print(xn)


(array([ 1,  3,  8, 10], dtype=int64),)


## search sorted array 

In [ ]:
# it will tell your nuber on position it will get set 

In [31]:
ar2= np.array([1,2,3,4,6,7,8,] )   

x1= np.searchsorted(ar2,5)

print(x1)    # it is tellin thta 5 will set at index n 4

4
