In [1]:
import numpy as np 

## matrix

In [3]:
ar2 = np.array([[1, 2, 3], [2, 3, 45]])

print(ar2)
print(type(ar2))

[[ 1  2  3]
 [ 2  3 45]]
<class 'numpy.ndarray'>


In [4]:
ar2 = np.matrix([[1, 2, 3], [2, 3, 45]]) 

print(ar2)
print(type(ar2))

[[ 1  2  3]
 [ 2  3 45]]
<class 'numpy.matrix'>


In [ ]:
# additon and substraction is same in matrix but problem is with mul

In [5]:
ar1 = np.matrix([[1, 2, 3], [2, 3, 45]]) 
ar2 = np.matrix([[1, 2, 3], [2, 3, 45]]) 


print(ar1+ar2)
print(type(ar2))

[[ 2  4  6]
 [ 4  6 90]]
<class 'numpy.matrix'>


In [6]:
ar1 = np.matrix([[1, 2, 3], [2, 3, 45]]) 
ar2 = np.matrix([[1, 2, 3], [2, 3, 45]]) 


print(ar1-ar2)
print(type(ar2))

[[0 0 0]
 [0 0 0]]
<class 'numpy.matrix'>


In [ ]:
# multipiaciton 

In [9]:
ar1 = np.matrix([[1, 2], [4, 3]]) 
ar2 = np.matrix([[1, 2 ], [4, 3]]) 


print(ar1*ar2)
print(type(ar2))

[[ 9  8]
 [16 17]]
<class 'numpy.matrix'>


In [10]:
ar1 = np.matrix([[1, 2], [4, 3]]) 
ar2 = np.matrix([[1, 2 ], [4, 3]]) 


print(ar1.dot(ar2))

[[ 9  8]
 [16 17]]


In [13]:
import numpy as np

ar3 = np.matrix([[1, 2, 3], [2, 3, 45]])
ar4 = np.matrix([[1, 2, 3], [2, 3, 45]])

# Matrix multiplication
result = ar3.dot(ar4.T)  # Transpose ar4 to match the dimensions

print(result)


[[  14  143]
 [ 143 2038]]
