## shuffle


In [1]:
import numpy as np

In [ ]:
# if you want to shuffle your data

In [3]:
ar5= np.array([4,5,6,7,8,0,0,6,1,2,3,4,4,6] )  
np.random.shuffle(ar5) 
print(ar5)

[0 6 4 5 4 2 3 6 6 4 8 0 1 7]


## unique

In [4]:
# unique data 

In [5]:
ar1= np.array([4,5,6,7,8,0,0,6,1,2,3,4,4,6] )  

x = np.unique(ar1) 
print(x)

[0 1 2 3 4 5 6 7 8]


In [6]:
# check unique no data index 

ar1= np.array([4,5,6,7,8,0,0,6,1,2,3,4,4,6] )  

x = np.unique(ar1 ,return_index=True) 
print(x)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([ 5,  8,  9, 10,  0,  1,  2,  3,  4], dtype=int64))


In [8]:
# you will get it counting  


ar1= np.array([4,5,6,7,8,0,0,6,1] )  

x = np.unique(ar1 ,return_index=True , return_counts=True) 
print(x)

(array([0, 1, 4, 5, 6, 7, 8]), array([5, 8, 0, 1, 2, 3, 4], dtype=int64), array([2, 1, 1, 1, 2, 1, 1], dtype=int64))


## resize 

In [22]:
# convert 1d to 2d 

In [10]:
ar1= np.array([4,5,6,7,8,0,0,6,1] )  

x1=np.resize(ar1 ,(3,2))      # it will resize in 3 R and 2 col
print(x1)

[[4 5]
 [6 7]
 [8 0]]


In [17]:
ar1= np.array([4,5,6,7,8,0,0,6,1,4,5,6,7,8,6,7,3,2,1,1,1,] )  

x1=np.resize(ar1 ,(5,5))      # it will resize in 3 R and 2 col
print(x1)

[[4 5 6 7 8]
 [0 0 6 1 4]
 [5 6 7 8 6]
 [7 3 2 1 1]
 [1 4 5 6 7]]


## flatten

In [ ]:
# convert  2d in 1d 

In [20]:
ar1= np.array([ [4,5,6,7,8,0,0,6,1] ] )   

x=ar1.flatten()
print(x)

[4 5 6 7 8 0 0 6 1]


## ravel

In [21]:
ar1= np.array([ [4,5,6,7,8,0,0,6,1] ] )   

x=ar1.ravel()
print(x)

[4 5 6 7 8 0 0 6 1]
