### shape

In [1]:
import numpy as np

In [3]:
ar1= np.array([[1,2,3,4] , 
               [5,6,7,8]]) 

print(ar1.shape)

(2, 4)


In [6]:
ar1= np.array([1,2,3,4] ) 

print(ar1.shape)

(4,)


In [9]:
ar1= np.array([1,2,3,4] ,ndmin=5) 

print(ar1)

print(ar1.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


## reshape

In [18]:
ar1= np.array([1,2,3,4,5,6] )  

print(ar1)
print(ar1.ndim)

print()
 
 
 
 
x=ar1.reshape(3,2) 

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [19]:
ar1= np.array([1,2,3,4,5,6,7,8,9,10,11,12] )   

x= ar1.reshape(3,2,2)   # 3d 

print(x)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
# convert from 3d array to 1d 

In [22]:
ar1= np.array([1,2,3,4,5,6,7,8,9,10,11,12] )   

x= ar1.reshape(3,2,2)   # 3d 

print(x) 

print() 
print()


new= x.reshape(-1)     # 1d

print(new)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


[ 1  2  3  4  5  6  7  8  9 10 11 12]


## brodcasting

In [2]:


# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])


result = arr_2d + 10

print("Original Array:")
print(arr_2d)
print("\nResult after Broadcasting:")
print(result)


Original Array:
[[1 2 3]
 [4 5 6]]

Result after Broadcasting:
[[11 12 13]
 [14 15 16]]


In [9]:
x=np.array([[2],
            [1]]) 


y= np.array([[1,2,3] ,
             [1,6,4]])

print(x.shape , y.shape)

(2, 1) (2, 3)


In [10]:
add = x+y
print(add)

[[3 4 5]
 [2 7 5]]
